# Time Series Prediction with Reservoir Computing ($RCN$)

AUTHOR: Anurag Dutta (anuragdutta.research@gmail.com)

SUPERVISOR: Tanujit Chakraborty (tanujit.chakraborty@sorbonne.ae)

CREATED: 2023-03-07 20:00:23

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


## Gathering Dependencies

_Importing Required Libraries_

In [2]:
pip install hampel

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [3]:
from keras.models import Sequential
from keras.layers import Dropout
from keras.layers import Dense
from keras.layers import LSTM
import keras
import tensorflow as tf
from hampel import hampel
import numpy as np
from numpy import array
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error

## Loading Datasets

_SAN JUAN_

In [13]:
data = pd.read_csv("/content/drive/MyDrive/new/datasets/sanjuan.csv")
training_set = data.iloc[:, 3]
print(training_set)

0        4
1        5
2        4
3        3
4        6
        ..
1191    56
1192    46
1193    52
1194    34
1195    25
Name: Cases, Length: 1196, dtype: int64


## Preprocessing the Data

In [14]:
# univariate data preparation
from numpy import array

# split a univariate sequence into samples
def split_sequence(sequence, n_steps):
	X, y = list(), list()
	for i in range(len(sequence)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the sequence
		if end_ix > len(sequence)-1:
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
		X.append(seq_x)
		y.append(seq_y)
	return array(X), array(y)

# choose a number of time steps
n_steps = 3
# split into samples
X, y = split_sequence(training_set, n_steps)
# summarize the data
for i in range(len(X)):
	print(X[i], y[i])

[4 5 4] 3
[5 4 3] 6
[4 3 6] 2
[3 6 2] 4
[6 2 4] 5
[2 4 5] 10
[ 4  5 10] 6
[ 5 10  6] 8
[10  6  8] 2
[6 8 2] 6
[8 2 6] 17
[ 2  6 17] 23
[ 6 17 23] 13
[17 23 13] 21
[23 13 21] 28
[13 21 28] 24
[21 28 24] 20
[28 24 20] 40
[24 20 40] 27
[20 40 27] 42
[40 27 42] 33
[27 42 33] 43
[42 33 43] 37
[33 43 37] 57
[43 37 57] 71
[37 57 71] 44
[57 71 44] 56
[71 44 56] 53
[44 56 53] 52
[56 53 52] 47
[53 52 47] 26
[52 47 26] 27
[47 26 27] 21
[26 27 21] 21
[27 21 21] 26
[21 21 26] 34
[21 26 34] 37
[26 34 37] 17
[34 37 17] 19
[37 17 19] 25
[17 19 25] 18
[19 25 18] 21
[25 18 21] 17
[18 21 17] 17
[21 17 17] 16
[17 17 16] 16
[17 16 16] 15
[16 16 15] 23
[16 15 23] 16
[15 23 16] 17
[23 16 17] 12
[16 17 12] 17
[17 12 17] 10
[12 17 10] 15
[17 10 15] 19
[10 15 19] 21
[15 19 21] 14
[19 21 14] 18
[21 14 18] 13
[14 18 13] 14
[18 13 14] 18
[13 14 18] 23
[14 18 23] 25
[18 23 25] 62
[23 25 62] 60
[25 62 60] 76
[62 60 76] 66
[60 76 66] 64
[76 66 64] 68
[66 64 68] 89
[64 68 89] 92
[68 89 92] 140
[ 89  92 140] 116
[ 92 1

## Model ($RCN$)

In [15]:
pip install reservoirpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [16]:
from reservoirpy.nodes import Reservoir, Ridge

reservoir = Reservoir(units=100, lr=0.5, sr=0.001)
readout = Ridge(output_dim=3, ridge=1e-8)

In [17]:
esn = reservoir >> readout

In [18]:
esn.fit(X[:954], X[1:955], warmup=100)

Running Model-1:   0%|          | 0/1 [00:00<?, ?it/s]
Running Model-1: 58it [00:00, 527.54it/s]             
Running Model-1: 111it [00:00, 410.23it/s]
Running Model-1: 154it [00:00, 414.03it/s]
Running Model-1: 197it [00:00, 397.62it/s]
Running Model-1: 238it [00:00, 355.50it/s]
Running Model-1: 280it [00:00, 364.95it/s]
Running Model-1: 321it [00:00, 374.90it/s]
Running Model-1: 359it [00:00, 372.86it/s]
Running Model-1: 411it [00:01, 410.91it/s]
Running Model-1: 480it [00:01, 485.75it/s]
Running Model-1: 530it [00:01, 457.34it/s]
Running Model-1: 577it [00:01, 418.89it/s]
Running Model-1: 620it [00:01, 380.59it/s]
Running Model-1: 660it [00:01, 362.79it/s]
Running Model-1: 697it [00:01, 354.87it/s]
Running Model-1: 733it [00:01, 351.08it/s]
Running Model-1: 775it [00:02, 355.83it/s]
Running Model-1: 811it [00:02, 353.29it/s]
Running Model-1: 854it [00:02, 370.55it/s]
Running Model-1: 954it [00:02, 399.48it/s]
Running Model-1: 100%|██████████| 1/1 [00:02<00:00,  2.46s/it]


Fitting node Ridge-1...


'Model-1': Model('Reservoir-1', 'Ridge-1')

In [19]:
predictions = esn.run(X[955:-1])

Running Model-1: 237it [00:00, 2178.82it/s]


## Metrics ($RCN$)

In [20]:
import reservoirpy.observables
from sklearn.metrics import mean_squared_error, mean_absolute_error

rmse = np.sqrt(mean_squared_error(X[955:-1], predictions))
mae = np.sqrt(mean_absolute_error(X[955:-1], predictions))
print('Test RMSE: %.3f' % rmse)
print('Test MAE: %.3f' % mae)

Test RMSE: 63.840
Test MAE: 6.207
